export default{
    LOGIN : 'LOGIN',
    LOGOUT : 'LOGOUT',
    FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
    FETCH_EVENTS_FAILURE: 'FETCH_EVENTS_FAILURE',
    FETCH_GALLERY_SUCCESS: 'FETCH_GALLERY_SUCCESS',
    FETCH_GALLERY_FAILURE: 'FETCH_GALLERY_FAILURE'
}